action_selector: ~
agent: grnn
agent_output_type: ~
batch_size_run: 1
batch_size: 32
buffer_size: 5000
exploration_mode: "gaussian"
gamma: 0.85
grad_norm_clip: 0.5
learner: "mcemncd_learner"
lr: 0.01
critic_lr: 0.01
td_lambda: 0.8
mac: mcemncd_mac
mixer: "qmix"
mixing_embed_dim: 128
skip_connections: False
gated: False
hypernet_layers: 2
hypernet_embed: 128
hyper_initialization_nonzeros: 0
name: "mcemncd_pp"
optimizer: adam
optimizer_epsilon: 0.01
critic_hidden_dim: 64
runner: "episode"
runner_scope: 'episodic'
target_update_mode: 'soft'
target_update_tau: 0.0005
test_interval: 2000
test_nepisode: 10
t_max: 2050000
weight_decay: True
weight_decay_factor: 0.0001
q_embed_dim: 1
learn_interval: 1

clip_stddev: 10
num_samples: 20
topk: 2
save_log_probs: True
tb_lambda: 1
entropy_coef: 0.1

